# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'

    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
    groups:
      # pkg.json "dependencies"
      prod-deps:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
        # excluding all 0.x leading-zero package (since dependabot consider eg: 0.7.3 -> 0.8.0 minor bump / as opposed to semver)
        exclude-patterns:
          - 'glsl-noise'
          - 'maath'
          - 'stats.js'
          - 'suspend-react'
          - 'three-mesh-bvh'
          - 'troika-three-text'
          - 'tunnel-rat'
      # pkg.json "devDependencies"
      dev-deps:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
        # excluding all 0.x leading-zero package (since dependabot consider eg: 0.7.3 -> 0.8.0 minor bump / as opposed to semver)
        exclude-patterns:
          - '@types/three'
          - 'eslint-plugin-storybook'
          - 'three'
